### ISSUE TITLE
help understanding

### ISSUE THREAD

**Issue by cornfeedhobo** [anisse/dmencrypt#1]
Can you help me understand the difference between using this vs using something like `dd` to create a file and then treat it like a block device?

**Comment by anisse** [comment]
This project does not need a working Linux kernel host, nor the privileges to be able to treat a file as a block device, and then use the host's dm-crypt.

**Comment by anisse** [comment]
Or to rephrase: you don't need to be root to create or decrypt a dm-crypt image.

And at the time of writing and publication, it was 1000 times faster than the only other userspace solution I was able to find.

Does that answer your question?

**Comment by cornfeedhobo** [comment]
Yes, I think it does. thank you.
